execute pathogen#infect()	

filetype plugin indent on
syntax enable


let g:gruvbox_italic = 1
colorscheme gruvbox		" Setting gruvbox color scheme 
set background=dark 		" Setting dark mode

set termguicolors

"let g:grubbox_contrast_dark = hard 
"let g:gruvbox_gruvbox_plugin_hi_groups = 1
"let g:gruvbox_filetype_hi_groups = 1

set laststatus=2
set noshowmode

let g:lightline = {
      \ 'colorscheme': 'gruvbox',
      \ }

" add yaml configs
" foldmethod=indent
au! BufNewFile,BufReadPost *.{yaml,yml} set filetype=yaml 
autocmd FileType yaml setlocal ts=2 sts=2 sw=2 expandtab


:set number relativenumber	" Relative line numbers

:augroup numbertoggle
:  autocmd!
:  autocmd BufEnter,FocusGained,InsertLeave * set relativenumber
:  autocmd BufLeave,FocusLost,InsertEnter   * set norelativenumber
:augroup END
