# Make some possibly destructive commands more interactive.
alias rm='rm -i'
alias mv='mv -i'
alias cp='cp -i'

alias ls='exa --color=auto'
alias ll='exa -l --color=auto'
alias la='exa -la --color=auto'

alias find='fd'

alias grep='grep --colour=auto'
alias egrep='egrep --colour=auto'
alias fgrep='fgrep --colour=auto'

alias vim='nvim'

alias clip='xclip -sel clip'
