#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

git_branch() {
  git branch 2>/dev/null | grep '^*' | colrm 1 2
}

# Prompt
PS1='\[\033[01;32m\][\u@\h\[\033[01;37m\] \W\[\033[01;32m\] $(git_branch)]\n \[\033[01;32m\]└─\[\033[\033[01;32m\] \$\[\033[00m\] '

# Bash history file location
HISTFILE='/home/locutor/.bash_history'

# Add bash aliases.
if [ -f ~/.bash_aliases ]; then
    source ~/.bash_aliases
fi

